# paths to files downloaded from NIST (not parsed)
raw_data:
  msp_dir: C:\Jack\Extracted NIST\FragPath\MSPs
  mol_dir: C:\Jack\Extracted NIST\FragPath\MOLs

# paths to databases
dbs:
  db_path: C:\Jack\FragTree\databases\reference\tms\metadata.db
  h5_path: C:\Jack\FragTree\databases\reference\tms\spectra.h5
  mol_h5_path: C:\Jack\FragTree\databases\reference\tms\structures.h5

# path to outputs
outputs:
  reports_dir: C:\Jack\FragTree\databases\reports